cloud.aws:
  region: ap-southeast-2
  reportS3Bucket: theater-dev
  reportDynamoDb: theater-premium-report-dev
server:
  port: 8080
spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportS3Bucket: theater-dev
  reportDynamoDb: theater-premium-report-dev

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportS3Bucket: theater-stg
  reportDynamoDb: theater-premium-report-stg

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportS3Bucket: theater-prod
  reportDynamoDb: theater-premium-report-stg