cloud.aws:
  region: ap-southeast-2
  reportS3Bucket: theater-dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:~/theater;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
server:
  port: 8081
cloud.aws:
  reportS3Bucket: theater-dev

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:h2:file:~/theater;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
server:
  port: 8081
cloud.aws:
  reportS3Bucket: theater-stg

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:~/theater;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
server:
  port: 8081
cloud.aws:
  reportS3Bucket: theater-prod